
fullTeam_shortCity_map = {
    '49ers':'SFO',
    'Bears':'CHI',
    'Bengals':'CIN',
    'Bills':'BUF',
    'Broncos':'DEN',
    'Browns':'CLE',
    'Buccaneers': 'TAM',
    'Cardinals': 'ARI',
    'Chargers': 'LAC',
    'Chiefs': 'KAN',
    'Colts': 'IND',
    'Cowboys': 'DAL',
    'Dolphins': 'MIA',
    'Eagles': 'PHI',
    'Falcons': 'ATL',
    'Giants': 'NYG',
    'Jaguars': 'JAX',
    'Jets': 'NYJ',
    'Lions': 'DET',
    'Packers': 'GNB',
    'Panthers': 'CAR',
    'Patriots': 'NWE',
    'Raiders': 'LVR',
    'Rams': 'LAR',
    'Ravens': 'BAL',
    'Redskins': 'WAS',
    'Football_Team':'WAS',
    'Saints': 'NOR',
    'Seahawks': 'SEA',
    'Steelers': 'PIT',
    'Texans': 'HOU',
    'Titans': 'TEN',
    'Vikings': 'MIN'
}

fullTeam_shortTeam_map = {
    'San Francisco 49ers':'49ers',
    'Chicago Bears':'Bears',
    'Cincinnati Bengals':'Bengals',
    'Buffalo Bills':'Bills',
    'Denver Broncos':'Broncos',
    'Cleveland Browns':'Browns',
    'Tampa Bay Buccaneers':'Buccaneers',
    'Arizona Cardinals':'Cardinals',
    'Los Angeles Chargers':'Chargers',
    'Kansas City Chiefs':'Chiefs',
    'Indianapolis Colts':'Colts',
    'Dallas Cowboys':'Cowboys',
    'Miami Dolphins':'Dolphins',
    'Philadelphia Eagles':'Eagles',
    'Atlanta Falcons':'Falcons',
    'New York Giants':'Giants',
    'Jacksonville Jaguars':'Jaguars',
    'New York Jets':'Jets',
    'Detroit Lions':'Lions',
    'Green Bay Packers':'Packers',
    'Carolina Panthers':'Panthers',
    'New England Patriots':'Patriots',
    'Las Vegas Raiders':'Raiders',
    'Los Angeles Rams':'Rams',
    'Baltimore Ravens':'Ravens',
    'Washington Football Team':'Football_Team',
    'New Orleans Saints':'Saints',
    'Seattle Seahawks':'Seahawks',
    'Pittsburgh Steelers':'Steelers',
    'Houston Texans':'Texans',
    'Tennessee Titans':'Titans',
    'Minnesota Vikings':'Vikings'
}